### ISSUE TITLE
no arch build support

### ISSUE THREAD

**Issue by todthetoad** [Ubuntufanboy/bad-apple#5]
can not install on arch

**Comment by Ubuntufanboy** [comment]
Sorry that I missed this issue! Arch is supported with the code. You may be missing dependencies.

**Comment by Ubuntufanboy** [comment]
I should elaborate. The dependencies are 
- yt-dlp (I know installing yt-dlp on arch is difficuly but it does work)
-Pillow (Install with pip3 install Pillow)
- ffmpeg (should be sudo pacman -S ffmpeg) *Assuming you don't already have ffmpeg installed*
- Silver (A sound player I made. Check it out here https://www.github.com/Ubuntufanboy/Silver.git)
- playsound (pip3 install playsound)
- and python ofc (prob sudo pacman -S python3)
